C_DEFINES=-D_GLFW_COCOA
C_INCLUDES=-I/sgoinfre/goinfre/Perso/coremart/glfw/include -I/sgoinfre/goinfre/Perso/coremart/glfw/src
C_FLAGS=-Wall -std=gnu99

all:
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -Wdeclaration-after-statement -o CMakeFiles/glfw.dir/context.c.o  -c /sgoinfre/goinfre/Perso/coremart/glfw/src/context.c
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -Wdeclaration-after-statement -o CMakeFiles/glfw.dir/init.c.o   -c /sgoinfre/goinfre/Perso/coremart/glfw/src/init.c
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -Wdeclaration-after-statement -o CMakeFiles/glfw.dir/input.c.o   -c /sgoinfre/goinfre/Perso/coremart/glfw/src/input.c
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -Wdeclaration-after-statement -o CMakeFiles/glfw.dir/monitor.c.o   -c /sgoinfre/goinfre/Perso/coremart/glfw/src/monitor.c
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -Wdeclaration-after-statement -o CMakeFiles/glfw.dir/vulkan.c.o   -c /sgoinfre/goinfre/Perso/coremart/glfw/src/vulkan.c
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -Wdeclaration-after-statement -o CMakeFiles/glfw.dir/window.c.o   -c /sgoinfre/goinfre/Perso/coremart/glfw/src/window.c
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/glfw.dir/cocoa_init.m.o   -c /sgoinfre/goinfre/Perso/coremart/glfw/src/cocoa_init.m
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/glfw.dir/cocoa_joystick.m.o   -c /sgoinfre/goinfre/Perso/coremart/glfw/src/cocoa_joystick.m
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/glfw.dir/cocoa_monitor.m.o   -c /sgoinfre/goinfre/Perso/coremart/glfw/src/cocoa_monitor.m
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/glfw.dir/cocoa_window.m.o   -c /sgoinfre/goinfre/Perso/coremart/glfw/src/cocoa_window.m
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/glfw.dir/cocoa_time.c.o   -c /sgoinfre/goinfre/Perso/coremart/glfw/src/cocoa_time.c
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/glfw.dir/posix_thread.c.o   -c /sgoinfre/goinfre/Perso/coremart/glfw/src/posix_thread.c
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/glfw.dir/nsgl_context.m.o   -c /sgoinfre/goinfre/Perso/coremart/glfw/src/nsgl_context.m
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/glfw.dir/egl_context.c.o   -c /sgoinfre/goinfre/Perso/coremart/glfw/src/egl_context.c
	gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/glfw.dir/osmesa_context.c.o   -c /sgoinfre/goinfre/Perso/coremart/glfw/src/osmesa_context.c
	ar rc libglfw3.a CMakeFiles/glfw.dir/context.c.o CMakeFiles/glfw.dir/init.c.o CMakeFiles/glfw.dir/input.c.o CMakeFiles/glfw.dir/monitor.c.o CMakeFiles/glfw.dir/vulkan.c.o CMakeFiles/glfw.dir/window.c.o CMakeFiles/glfw.dir/cocoa_init.m.o CMakeFiles/glfw.dir/cocoa_joystick.m.o CMakeFiles/glfw.dir/cocoa_monitor.m.o CMakeFiles/glfw.dir/cocoa_window.m.o CMakeFiles/glfw.dir/cocoa_time.c.o CMakeFiles/glfw.dir/posix_thread.c.o CMakeFiles/glfw.dir/nsgl_context.m.o CMakeFiles/glfw.dir/egl_context.c.o CMakeFiles/glfw.dir/osmesa_context.c.o
	ranlib libglfw3.a

